#line 2 "1905001_scanner.c"

#line 4 "1905001_scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[278] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       76,   74,    1,    2,    1,   46,   56,   29,   41,   55,
       47,   48,   27,   25,   53,   26,   74,   28,   19,   54,
       32,   38,   34,   23,   23,   51,   52,   43,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   49,   42,
       50,   62,   60,   62,   61,   62,   67,   65,   67,   66,
       67,   73,   71,   73,   70,   68,   70,   70,    1,    2,
       37,   39,   30,    0,    0,   31,    0,   21,   20,   22,
       58,   57,   20,   19,   24,   22,   44,   33,   36,   35,
       45,   23,   23,   23,   23,   23,   23,   23,    7,   23,

       23,   23,    3,   23,   23,   23,   23,   23,   40,   60,
       59,   65,   64,    0,   63,   72,   68,   69,    0,   21,
       21,   21,   20,   22,   22,   20,   22,   20,   19,   22,
        0,    0,   20,   22,   23,   23,   23,   23,   23,   23,
       23,   23,    5,    9,   23,   23,   23,   23,   21,   21,
       20,   22,    0,   20,   22,   20,   22,    0,   20,   22,
        0,   20,   20,   22,   22,   20,   22,   24,   23,   16,
       10,   23,   23,   23,    4,   23,   23,   23,   13,   23,
       21,   21,   21,   21,   21,    0,   20,   20,   20,   22,
        0,    0,   20,   20,   20,    0,   20,   20,   20,   20,

       22,   22,    0,   22,    0,    0,   22,   22,   24,   24,
        8,   23,   23,   23,   11,   23,   23,    6,   21,   21,
       21,   21,   21,   21,   20,   20,    0,   22,   21,    0,
       20,   20,   20,   20,   20,   20,   22,    0,    0,    0,
       22,   22,   22,   22,   22,   22,   24,   23,   23,   12,
       14,   15,   21,   21,   21,   21,   22,   21,   20,   22,
        0,    0,    0,   22,   22,   23,   17,   21,   21,   21,
       22,   22,   22,   18,   21,   22,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   24,   37,   38,   24,   39,   40,   24,   41,
       42,   24,   24,   43,   44,   45,   46,   47,   48,   24,
       24,   24,   49,   50,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    2,    2,    1,    3,    1,    1,    3,    1,
        1,    1,    4,    1,    4,    4,    1,    5,    6,    1,
        1,    1,    1,    6,    6,    1,    3,    1,    1,    6,
        5,    5,    6,    6,    6,    5,    6,    6,    6,    6,
        5,    6,    5,    6,    5,    6,    5,    6,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[286] =
    {   0,
        0,    0,   49,   51,   53,   58,   60,   62,   63,   65,
      295, 1432,   69, 1432,   79,  272, 1432, 1432,  285, 1432,
     1432, 1432, 1432,   78, 1432,   86,   99,   58,  107, 1432,
       65,  270,   66,    0,  120, 1432, 1432, 1432,  248,  106,
       42,  243,   58,  105,  245,  226,  231,  235, 1432,  221,
     1432, 1432, 1432,  267, 1432,    0, 1432, 1432,  259, 1432,
      103, 1432, 1432,  242, 1432, 1432,  250,  105,  125, 1432,
     1432, 1432,  134,  145,  158,  166,  179,  187,  200,  208,
     1432, 1432,  221,  229,  115,  242, 1432, 1432, 1432, 1432,
     1432,    0,    0,  217,  207,  219,  208,  205,  192,  188,

      189,  187,    0,  184,  183,  182,  179,  173, 1432, 1432,
     1432, 1432, 1432,  207, 1432, 1432, 1432, 1432,  206,  250,
      263,  271,  284,  292,  305,  313,  326,  334,    0,  345,
      352,  360,  364,  373,  177,  172,  156,  151,  159,  157,
      153,  156,    0,    0,  140,  133,  141,  132,  385,  393,
      406,  414,  427,  435,  448,  456,  469,  477,  490,  498,
      511,  503,  524,  532,  545,  537,  556,  560,  129,    0,
        0,  129,  120,  125,    0,  117,  114,  123,    0,  119,
      568,  581,  589,  602,  610,  623,  631,  644,  652,  665,
      673,  686,  694,  707,  715,  728,  736,  749,  741,  762,

      770,  783,  791,  804,  812,  825,  817,  838,  830,  851,
        0,  110,  104,  105,    0,   78,   79,    0,  859,  872,
      880,  893,  901,  914,  922,  935,  943,  956,  964,  977,
      985,  998, 1006, 1019, 1027, 1040, 1048, 1061, 1069, 1082,
     1090, 1103, 1111, 1115, 1126, 1137, 1139,   64,   50,    0,
        0,    0, 1150, 1158, 1171, 1179, 1192, 1200, 1213, 1221,
     1234, 1242, 1255, 1263, 1276,   44,    0, 1284, 1297, 1305,
     1318, 1326, 1339,    0, 1347, 1360, 1432, 1395, 1401, 1407,
     1413, 1416, 1418, 1422, 1426
    } ;

static const flex_int16_t yy_def[286] =
    {   0,
      277,    1,  278,  278,  279,  279,  280,  280,  281,  281,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  282,  277,
      277,  277,  277,  283,  283,  277,  277,  277,  283,  283,
      283,   35,  283,  283,  283,  283,  283,  283,  277,  277,
      277,  277,  277,  277,  277,  284,  277,  277,  277,  277,
      285,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  282,  282,  282,  277,  277,  277,  277,
      277,  283,   35,  283,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,   84,   86,
      277,  277,   84,   86,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,   84,  277,  277,  277,   84,   86,   84,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,   84,  277,

      277,  277,  277,  277,  277,  277,   84,  277,   84,   84,
      283,  283,  283,  283,  283,  283,  283,  283,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,   84,  277,   84,  210,  283,  283,  283,
      283,  283,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  283,  283,  277,  277,  277,
      277,  277,  277,  283,  277,  277,    0,  277,  277,  277,
      277,  277,  277,  277,  277
    } ;

static const flex_int16_t yy_nxt[1484] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   30,
       31,   32,   33,   34,   35,   36,   12,   37,   38,   34,
       34,   39,   40,   41,   42,   43,   34,   44,   34,   34,
       34,   34,   45,   46,   34,   34,   47,   48,   49,   50,
       51,   53,   54,   53,   54,   58,   59,   55,   60,   55,
       58,   59,   63,   60,   63,   66,   67,   66,   67,   81,
       69,   64,   69,   64,   82,   56,   98,   56,  274,   61,
       69,   70,   69,   99,   61,   87,   88,   90,   91,   68,
       73,   68,   74,   75,  267,   74,   74,  101,   74,  102,

       76,   75,   74,   74,   74,  113,  114,  118,  119,  266,
       74,   77,   74,   77,   78,  252,   79,   79,  251,   74,
       74,   74,   83,   80,   84,   84,   69,  277,   69,  277,
      277,   86,   74,   80,   74,   75,   95,   93,   93,  250,
      103,   86,   96,  249,   93,  104,   74,   97,   74,   75,
      248,   74,   74,  218,   93,  217,  216,   74,   74,   74,
       75,  215,   74,   74,  214,  213,  212,  211,   74,   74,
       77,  180,   77,   78,  179,   77,   77,  178,   74,   74,
       74,   75,   77,   74,   74,  177,  176,  175,  174,  173,
       74,   77,   77,   77,   78,  172,   77,   77,  171,  120,

       74,  120,  121,   77,  120,  120,  170,  169,  118,  113,
      148,  120,   77,   77,   77,  122,  147,  123,  123,  146,
       77,  120,   77,   78,  124,  125,  125,  145,  144,  143,
      142,  141,   77,   77,  124,   77,  122,  140,  126,  126,
      139,   74,   77,   74,  128,  127,  129,  129,  138,  137,
      136,  135,  117,  130,  131,  127,  131,  132,  116,  133,
      133,  112,  120,  130,  120,  121,  134,  120,  120,  110,
      109,  108,  107,  106,  120,  120,  134,  120,  121,  105,
      120,  120,  100,  120,  120,  120,  121,  120,  149,  149,
       94,   89,   72,   71,  277,  120,   77,  120,   77,  150,

      277,  151,  151,  277,  153,  120,  153,  122,  152,  154,
      154,  277,  277,  277,  277,  277,  155,   77,  152,   77,
       78,  277,  125,  125,  277,   77,  155,   77,  150,   77,
      156,  156,  277,  277,  277,  277,  277,  157,  158,   77,
      158,  122,  277,  159,  159,  277,   77,  157,   77,  122,
      155,  156,  156,  277,  277,  277,  277,  161,  160,  161,
      155,  277,  162,  162,   74,  277,   74,   75,  160,  163,
      163,  277,   77,  277,   77,   78,   74,  164,  164,  165,
      277,  166,  166,  277,   77,   74,   74,   74,  167,  277,
      168,  168,  277,  277,   77,  277,  277,  120,  167,  120,

      181,  277,  182,  182,  277,  120,  277,  120,  181,  183,
      184,  184,  277,  277,  277,  277,  277,  185,   77,  183,
       77,  150,  277,  151,  151,  277,  186,  185,  186,  122,
      152,  187,  187,  277,  277,  277,  277,  277,  155,   77,
      152,   77,   78,  277,  188,  188,  277,   77,  155,   77,
      150,   77,  189,  189,  277,  277,  277,  277,  277,  190,
       77,   77,   77,  122,  277,  191,  191,  277,   77,  190,
       77,  150,  155,  156,  156,  277,  277,  277,  277,  277,
      157,  192,  155,  192,  122,  277,  193,  193,  277,   77,
      157,   77,   78,  155,  194,  194,  277,  277,  277,  277,

      277,   77,   77,  155,   77,  150,  277,  195,  195,  277,
      196,   77,  196,  122,  190,  197,  197,  277,  165,  277,
      199,  199,  155,   74,  190,   74,   75,  167,  198,  198,
      277,  277,  155,  277,  277,   74,   74,  167,   74,  132,
      277,  200,  200,  277,   77,   74,   77,  122,  201,  202,
      202,  277,  165,  277,  166,  166,  203,   77,  201,   77,
      122,  167,  204,  204,  277,  277,  203,  277,  206,  205,
      206,  167,  277,  207,  207,  208,  277,  209,  209,  205,
      120,  277,  120,  121,  210,  149,  149,  277,  277,  277,
      277,  277,  120,  120,  210,  120,  219,  277,  184,  184,

      277,  221,  120,  221,  121,  220,  222,  222,  277,  277,
      277,  277,  277,  120,  120,  220,  120,  219,  277,  184,
      184,  277,  223,  120,  223,  121,  220,  224,  224,  277,
      277,  277,  277,  277,  120,   77,  220,   77,   78,  277,
      225,  225,  277,   77,  120,   77,  150,   77,  226,  226,
      277,  277,  277,  277,  277,  190,   77,   77,   77,  122,
      277,  154,  154,  277,   77,  190,   77,  150,  155,  189,
      189,  277,  277,  277,  277,  277,  190,  227,  155,  227,
      122,  277,  228,  228,  277,   77,  190,   77,  229,  155,
      230,  230,  277,  277,  277,  277,  277,  205,   77,  155,

       77,   78,  277,  231,  231,  277,   77,  205,   77,  150,
       77,  232,  232,  277,  277,  277,  277,  277,  190,   77,
       77,   77,  122,  277,  159,  159,  277,   77,  190,   77,
      150,  155,  195,  195,  277,  277,  277,  277,  277,  190,
       77,  155,   77,   78,  277,  233,  233,  277,   77,  190,
       77,  150,   77,  234,  234,  277,  165,  277,  199,  199,
      190,   74,   77,   74,  132,  167,  235,  235,  277,  277,
      190,  277,  277,  201,   74,  167,   74,  165,  277,  236,
      236,  277,   74,  201,   74,  132,  237,  238,  238,  277,
      277,  277,  277,  277,  201,   77,  237,   77,  150,  277,

      204,  204,  277,  240,  201,  240,   78,  239,  241,  241,
      277,  277,  277,  277,  277,   77,   77,  239,   77,  150,
      277,  204,  204,  277,  227,   77,  227,   78,  239,  242,
      242,  277,  165,  277,  244,  244,   77,   74,  239,   74,
       75,  210,  243,  243,  277,  208,   77,  209,  209,   74,
       77,  210,   77,  122,  210,  245,  245,  277,  277,   74,
      277,  277,  205,  206,  210,  206,   75,  277,  246,  246,
      277,  120,  205,  120,  181,  247,  184,  184,  277,  277,
      277,  277,  277,  185,  253,  247,  253,  121,  277,  254,
      254,  277,  120,  185,  120,  121,  120,  222,  222,  277,

      277,  277,  277,  277,  120,  120,  120,  120,  181,  277,
      255,  255,  277,  120,  120,  120,  121,  120,  224,  224,
      277,  277,  277,  277,  277,  120,  120,  120,  120,  181,
      277,  256,  256,  277,   77,  120,   77,  122,  120,  187,
      187,  277,  277,  277,  277,  277,  155,   77,  120,   77,
      150,  277,  226,  226,  277,   77,  155,   77,   78,  190,
      242,  242,  277,  277,  277,  277,  277,   77,   77,  190,
       77,  150,  277,  257,  257,  277,  120,   77,  120,  181,
      205,  258,  258,  277,  277,  277,  277,  277,  185,   77,
      205,   77,  229,  277,  230,  230,  277,   77,  185,   77,

      122,  205,  193,  193,  277,  277,  277,  277,  277,  155,
       77,  205,   77,  150,  277,  232,  232,  277,   77,  155,
       77,  122,  190,  197,  197,  277,  277,  277,  277,  277,
      155,   77,  190,   77,  150,  277,  234,  234,  277,   74,
      155,   74,  165,  190,  259,  259,  277,  277,  277,  277,
      277,  237,   74,  190,   74,  165,  277,  236,  236,  277,
      206,  237,  206,  132,  237,  260,  260,  277,  277,  277,
      277,  277,  201,   74,  237,   74,  208,  277,  261,  261,
      277,  263,  201,  263,   78,  262,  264,  264,  277,  277,
      277,  277,  277,   77,   77,  262,   77,   78,  277,  241,

      241,  277,   77,   77,   77,  122,   77,  265,  265,  277,
      277,  277,  277,  277,   77,   77,   77,   77,  122,  277,
      228,  228,  277,   74,   77,   74,  132,   77,  260,  260,
      165,  277,  244,  244,  277,   74,  277,   77,   77,  210,
       77,  150,  277,  245,  245,   74,  277,  277,  277,  210,
      205,   74,  132,   74,  207,  207,  247,  247,  277,  277,
      205,  247,  120,  277,  120,  121,  277,  254,  254,  277,
      120,  247,  120,  181,  120,  268,  268,  277,  277,  277,
      277,  277,  120,  120,  120,  120,  219,  277,  269,  269,
      277,  120,  120,  120,  219,  185,  270,  270,  277,  277,

      277,  277,  277,  185,   77,  185,   77,  150,  277,  257,
      257,  277,  120,  185,  120,  219,  205,  258,  258,  277,
      277,  277,  277,  277,  185,   74,  205,   74,  165,  277,
      259,  259,  277,   74,  185,   74,  165,  237,  271,  271,
      277,  277,  277,  277,  277,  262,   74,  237,   74,  208,
      277,  261,  261,  277,  206,  262,  206,   75,  262,  243,
      243,  277,  277,  277,  277,  277,   74,   77,  262,   77,
       78,  277,  264,  264,  277,   77,   74,   77,  122,   77,
      272,  272,  277,  277,  277,  277,  277,   77,   77,   77,
       77,  150,  277,  273,  273,  277,  120,   77,  120,  219,

      205,  275,  275,  277,  277,  277,  277,  277,  185,  120,
      205,  120,  219,  277,  269,  269,  277,  120,  185,  120,
      219,  185,  270,  270,  277,  277,  277,  277,  277,  185,
       74,  185,   74,  165,  277,  271,  271,  277,   77,  185,
       77,  150,  262,  276,  276,  277,  277,  277,  277,  277,
      205,   77,  262,   77,  150,  277,  273,  273,  277,  120,
      205,  120,  219,  205,  275,  275,  277,  277,  277,  277,
      277,  185,   77,  205,   77,  150,  277,  276,  276,  277,
      277,  185,  277,  277,  205,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  205,   52,   52,   52,   52,   52,

       52,   57,   57,   57,   57,   57,   57,   62,   62,   62,
       62,   62,   62,   65,   65,   65,   65,   65,   65,   85,
       85,   85,   92,   92,  111,  277,  111,  115,  115,  277,
      115,   11,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277
    } ;

static const flex_int16_t yy_chk[1484] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    4,    4,    5,    5,    3,    5,    4,
        6,    6,    7,    6,    8,    9,    9,   10,   10,   28,
       13,    7,   13,    8,   28,    3,   41,    4,  266,    5,
       15,   15,   15,   41,    6,   31,   31,   33,   33,    9,
       24,   10,   24,   24,  249,   24,   24,   43,   26,   43,

       26,   26,   24,   26,   26,   61,   61,   68,   68,  248,
       26,   27,   24,   27,   27,  217,   27,   27,  216,   29,
       26,   29,   29,   27,   29,   29,   69,   85,   69,   85,
       85,   29,   35,   27,   35,   35,   40,   35,   35,  214,
       44,   29,   40,  213,   35,   44,   73,   40,   73,   73,
      212,   73,   73,  180,   35,  178,  177,   74,   73,   74,
       74,  176,   74,   74,  174,  173,  172,  169,   73,   74,
       75,  148,   75,   75,  147,   75,   75,  146,   76,   74,
       76,   76,   75,   76,   76,  145,  142,  141,  140,  139,
       76,   77,   75,   77,   77,  138,   77,   77,  137,   78,

       76,   78,   78,   77,   78,   78,  136,  135,  119,  114,
      108,   78,   79,   77,   79,   79,  107,   79,   79,  106,
       80,   78,   80,   80,   79,   80,   80,  105,  104,  102,
      101,  100,   80,   83,   79,   83,   83,   99,   83,   83,
       98,   84,   80,   84,   84,   83,   84,   84,   97,   96,
       95,   94,   67,   84,   86,   83,   86,   86,   64,   86,
       86,   59,  120,   84,  120,  120,   86,  120,  120,   54,
       50,   48,   47,   46,  120,  121,   86,  121,  121,   45,
      121,  121,   42,  122,  120,  122,  122,  121,  122,  122,
       39,   32,   19,   16,   11,  122,  123,  121,  123,  123,

        0,  123,  123,    0,  124,  122,  124,  124,  123,  124,
      124,    0,    0,    0,    0,    0,  124,  125,  123,  125,
      125,    0,  125,  125,    0,  126,  124,  126,  126,  125,
      126,  126,    0,    0,    0,    0,    0,  126,  127,  125,
      127,  127,    0,  127,  127,    0,  128,  126,  128,  128,
      127,  128,  128,    0,    0,    0,    0,  130,  128,  130,
      127,    0,  130,  130,  131,    0,  131,  131,  128,  131,
      131,    0,  132,    0,  132,  132,  131,  132,  132,  133,
        0,  133,  133,    0,  132,  134,  131,  134,  133,    0,
      134,  134,    0,    0,  132,    0,    0,  149,  133,  149,

      149,    0,  149,  149,    0,  150,    0,  150,  150,  149,
      150,  150,    0,    0,    0,    0,    0,  150,  151,  149,
      151,  151,    0,  151,  151,    0,  152,  150,  152,  152,
      151,  152,  152,    0,    0,    0,    0,    0,  152,  153,
      151,  153,  153,    0,  153,  153,    0,  154,  152,  154,
      154,  153,  154,  154,    0,    0,    0,    0,    0,  154,
      155,  153,  155,  155,    0,  155,  155,    0,  156,  154,
      156,  156,  155,  156,  156,    0,    0,    0,    0,    0,
      156,  157,  155,  157,  157,    0,  157,  157,    0,  158,
      156,  158,  158,  157,  158,  158,    0,    0,    0,    0,

        0,  158,  159,  157,  159,  159,    0,  159,  159,    0,
      160,  158,  160,  160,  159,  160,  160,    0,  162,    0,
      162,  162,  160,  161,  159,  161,  161,  162,  161,  161,
        0,    0,  160,    0,    0,  161,  163,  162,  163,  163,
        0,  163,  163,    0,  164,  161,  164,  164,  163,  164,
      164,    0,  166,    0,  166,  166,  164,  165,  163,  165,
      165,  166,  165,  165,    0,    0,  164,    0,  167,  165,
      167,  166,    0,  167,  167,  168,    0,  168,  168,  165,
      181,    0,  181,  181,  168,  181,  181,    0,    0,    0,
        0,    0,  181,  182,  168,  182,  182,    0,  182,  182,

        0,  183,  181,  183,  183,  182,  183,  183,    0,    0,
        0,    0,    0,  183,  184,  182,  184,  184,    0,  184,
      184,    0,  185,  183,  185,  185,  184,  185,  185,    0,
        0,    0,    0,    0,  185,  186,  184,  186,  186,    0,
      186,  186,    0,  187,  185,  187,  187,  186,  187,  187,
        0,    0,    0,    0,    0,  187,  188,  186,  188,  188,
        0,  188,  188,    0,  189,  187,  189,  189,  188,  189,
      189,    0,    0,    0,    0,    0,  189,  190,  188,  190,
      190,    0,  190,  190,    0,  191,  189,  191,  191,  190,
      191,  191,    0,    0,    0,    0,    0,  191,  192,  190,

      192,  192,    0,  192,  192,    0,  193,  191,  193,  193,
      192,  193,  193,    0,    0,    0,    0,    0,  193,  194,
      192,  194,  194,    0,  194,  194,    0,  195,  193,  195,
      195,  194,  195,  195,    0,    0,    0,    0,    0,  195,
      196,  194,  196,  196,    0,  196,  196,    0,  197,  195,
      197,  197,  196,  197,  197,    0,  199,    0,  199,  199,
      197,  198,  196,  198,  198,  199,  198,  198,    0,    0,
      197,    0,    0,  198,  200,  199,  200,  200,    0,  200,
      200,    0,  201,  198,  201,  201,  200,  201,  201,    0,
        0,    0,    0,    0,  201,  202,  200,  202,  202,    0,

      202,  202,    0,  203,  201,  203,  203,  202,  203,  203,
        0,    0,    0,    0,    0,  203,  204,  202,  204,  204,
        0,  204,  204,    0,  205,  203,  205,  205,  204,  205,
      205,    0,  207,    0,  207,  207,  205,  206,  204,  206,
      206,  207,  206,  206,    0,  209,  205,  209,  209,  206,
      208,  207,  208,  208,  209,  208,  208,    0,    0,  206,
        0,    0,  208,  210,  209,  210,  210,    0,  210,  210,
        0,  219,  208,  219,  219,  210,  219,  219,    0,    0,
        0,    0,    0,  219,  220,  210,  220,  220,    0,  220,
      220,    0,  221,  219,  221,  221,  220,  221,  221,    0,

        0,    0,    0,    0,  221,  222,  220,  222,  222,    0,
      222,  222,    0,  223,  221,  223,  223,  222,  223,  223,
        0,    0,    0,    0,    0,  223,  224,  222,  224,  224,
        0,  224,  224,    0,  225,  223,  225,  225,  224,  225,
      225,    0,    0,    0,    0,    0,  225,  226,  224,  226,
      226,    0,  226,  226,    0,  227,  225,  227,  227,  226,
      227,  227,    0,    0,    0,    0,    0,  227,  228,  226,
      228,  228,    0,  228,  228,    0,  229,  227,  229,  229,
      228,  229,  229,    0,    0,    0,    0,    0,  229,  230,
      228,  230,  230,    0,  230,  230,    0,  231,  229,  231,

      231,  230,  231,  231,    0,    0,    0,    0,    0,  231,
      232,  230,  232,  232,    0,  232,  232,    0,  233,  231,
      233,  233,  232,  233,  233,    0,    0,    0,    0,    0,
      233,  234,  232,  234,  234,    0,  234,  234,    0,  235,
      233,  235,  235,  234,  235,  235,    0,    0,    0,    0,
        0,  235,  236,  234,  236,  236,    0,  236,  236,    0,
      237,  235,  237,  237,  236,  237,  237,    0,    0,    0,
        0,    0,  237,  238,  236,  238,  238,    0,  238,  238,
        0,  239,  237,  239,  239,  238,  239,  239,    0,    0,
        0,    0,    0,  239,  240,  238,  240,  240,    0,  240,

      240,    0,  241,  239,  241,  241,  240,  241,  241,    0,
        0,    0,    0,    0,  241,  242,  240,  242,  242,    0,
      242,  242,    0,  243,  241,  243,  243,  242,  243,  243,
      244,    0,  244,  244,    0,  243,    0,  242,  245,  244,
      245,  245,    0,  245,  245,  243,    0,    0,    0,  244,
      245,  247,  246,  247,  246,  246,  247,  247,    0,    0,
      245,  246,  253,    0,  253,  253,    0,  253,  253,    0,
      254,  246,  254,  254,  253,  254,  254,    0,    0,    0,
        0,    0,  254,  255,  253,  255,  255,    0,  255,  255,
        0,  256,  254,  256,  256,  255,  256,  256,    0,    0,

        0,    0,    0,  256,  257,  255,  257,  257,    0,  257,
      257,    0,  258,  256,  258,  258,  257,  258,  258,    0,
        0,    0,    0,    0,  258,  259,  257,  259,  259,    0,
      259,  259,    0,  260,  258,  260,  260,  259,  260,  260,
        0,    0,    0,    0,    0,  260,  261,  259,  261,  261,
        0,  261,  261,    0,  262,  260,  262,  262,  261,  262,
      262,    0,    0,    0,    0,    0,  262,  263,  261,  263,
      263,    0,  263,  263,    0,  264,  262,  264,  264,  263,
      264,  264,    0,    0,    0,    0,    0,  264,  265,  263,
      265,  265,    0,  265,  265,    0,  268,  264,  268,  268,

      265,  268,  268,    0,    0,    0,    0,    0,  268,  269,
      265,  269,  269,    0,  269,  269,    0,  270,  268,  270,
      270,  269,  270,  270,    0,    0,    0,    0,    0,  270,
      271,  269,  271,  271,    0,  271,  271,    0,  272,  270,
      272,  272,  271,  272,  272,    0,    0,    0,    0,    0,
      272,  273,  271,  273,  273,    0,  273,  273,    0,  275,
      272,  275,  275,  273,  275,  275,    0,    0,    0,    0,
        0,  275,  276,  273,  276,  276,    0,  276,  276,    0,
        0,  275,    0,    0,  276,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  276,  278,  278,  278,  278,  278,

      278,  279,  279,  279,  279,  279,  279,  280,  280,  280,
      280,  280,  280,  281,  281,  281,  281,  281,  281,  282,
      282,  282,  283,  283,  284,    0,  284,  285,  285,    0,
      285,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1905001_scanner.l"




#line 9 "1905001_scanner.l"
	
#include<cstdio>
#include<cstdlib>
#include<vector>
#include "1905001_symbol_table.h"

using namespace std;

#define BUCKET_SIZE 10

int line_count = 1;
int error_count = 0;

ofstream logout;
ofstream tokenout;

// if a string stretches multiple lines, we need to show the starting line no in case of token printing, 
// hence we need to keep the line no. unchanged while the string is running
int inside_line = 0; 

// in case of printing character and strings, if it is unfinished then we print
// characters like \n \b as they are (not their original behaviour), but if they are 
// completed properly, then \n will be replaced by NEWLINE...

string cur_char, cur_char_raw;
string cur_string, cur_string_raw;
string cur_comment;
int char_len; // will hold the length of the original one, not raw one

enum error_type {
		MULTICHAR, EMPTY_CHAR, UNFINISHED_CHAR, UNRECOGNIZED, TOO_DECIMAL, 
		ILL_FORMED, INVALID_SUFFIX, UNFINISHED_STRING, UNFINISHED_COMMENT
	};
enum num_type {INTEGER, FLOAT};
enum line_type {SINGLE_LINE, MULTILINE};
enum reset_type {CHAR, STRING, COMMENT};

SymbolTable sym(BUCKET_SIZE);

char generate_special_character(char c) {
	// MISC [ntafbvr0\'\"\\]
	if (c == 'n') return '\n';
	else if (c == 't') return '\t';
	else if (c == 'a') return '\a';
	else if (c == 'f') return '\f';
	else if (c == 'b') return '\b';
	else if (c == 'v') return '\v';
	else if (c == 'r') return '\r';
	else if (c == '0') return '\0';
	else return c;
}

void reset(reset_type rt) {
	inside_line = 0;
	if (rt == CHAR) {
		cur_char.clear();
		cur_char_raw.clear();
		char_len = 0;
	}
	else if (rt == STRING) {
		cur_string.clear();
		cur_string_raw.clear();
	}
	else if (rt == COMMENT) {
		cur_comment.clear();
	}
}

string capitalize(const string& s) {
	string ret = s;
	for (char& c : ret) c = toupper(c);
	return ret;
}

void printKeyword() {
	string cap = capitalize(yytext);
	tokenout << "<" << cap << ", " << yytext << ">" << endl;
	logout << "Line# " << line_count << ": Token <" << cap << "> Lexeme " << yytext << " found" << endl;
}

void printIdentifier() {
	logout << "Line# " << line_count << ": Token <ID> Lexeme " << yytext << " found" << endl;
	tokenout << "<ID, " << yytext << ">" << endl;
	bool success = sym.insert(yytext, "ID", logout);
	if (success) sym.print('A', logout);
}

void printNum(num_type nt, const string& str) {
	if (nt == INTEGER) {
		tokenout << "<CONST_INT, " << str << ">" << endl;
		logout << "Line# " << line_count << ": Token <CONST_INT> Lexeme " << str << " found" << endl;
	}
	else if (nt == FLOAT) {
		tokenout << "<CONST_FLOAT, " << str << ">" << endl;
		logout << "Line# " << line_count << ": Token <CONST_FLOAT> Lexeme " << str << " found" << endl;
	}
}

void printOpPunc(const string& token) {
	tokenout << "<" << token << ", " << yytext << ">" << endl;
	logout << "Line# " << line_count << ": Token <" << token << "> Lexeme " << yytext << " found" << endl;	
}

void printChar(const string& str) {
	tokenout << "<CONST_CHAR, " << str << ">" << endl;
	logout << "Line# " << line_count << ": Token <CONST_CHAR> Lexeme " << str << " found" << endl;
}

void printString(line_type lt, const string& str1, const string& str2) {
	if (lt == SINGLE_LINE) {
		logout << "Line# " << line_count << ": Token <SINGLE LINE STRING> Lexeme " << str1 << " found" << endl;
		tokenout << "<SINGLE LINE STRING, " << str2 << ">" << endl; 
	}
	else if (lt == MULTILINE) {
		logout << "Line# " << line_count << ": Token <MULTI LINE STRING> Lexeme " << str1 << " found" << endl;
		tokenout << "<MULTI LINE STRING, " << str2 << ">" << endl;
	}
}

void printComment(line_type lt, const string& str) {
	if (lt == SINGLE_LINE) {
		logout << "Line# " << line_count << ": Token <SINGLE LINE COMMENT> Lexeme " << str << " found" << endl;
	}
	else if (lt == MULTILINE) {
		logout << "Line# " << line_count << ": Token <MULTI LINE COMMENT> Lexeme " << str << " found" << endl;
	}
}

void show_error(error_type e, const string& str) {
	error_count++;

	logout << "Error at line# " << line_count << ": ";
	
	if (e == MULTICHAR) {
		logout << "MULTICHAR_CONST_CHAR " << str << endl;
	}
	else if (e == EMPTY_CHAR) {
		logout << "EMPTY_CONST_CHAR " << str << endl;
	}
	else if (e == UNFINISHED_CHAR) {
		logout << "UNFINISHED_CONST_CHAR " << str << endl;
	}
	else if (e == UNRECOGNIZED) {
		logout << "UNRECOGNIZED_CHAR " << str << endl;
	}
	else if (e == TOO_DECIMAL) {
		logout << "TOO_MANY_DECIMAL_POINTS " << str << endl;
	}
	else if (e == ILL_FORMED) {
		logout << "ILLFORMED_NUMBER " << str << endl;
	}
	else if (e == INVALID_SUFFIX) {
		logout << "INVALID_ID_SUFFIX_NUM_PREFIX " << str << endl;
	}
	else if (e == UNFINISHED_STRING) {
		logout << "UNFINISHED_STRING " << str << endl;
	}
	else if (e == UNFINISHED_COMMENT) {
		logout << "UNFINISHED_COMMENT " << str << endl;
	}
}

#line 1030 "1905001_scanner.c"
#line 1031 "1905001_scanner.c"

#define INITIAL 0
#define STATE_CHAR 1
#define STATE_STRING 2
#define C_COMMENT 3
#define CPP_COMMENT 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 195 "1905001_scanner.l"


#line 1255 "1905001_scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 278 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1432 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 197 "1905001_scanner.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 198 "1905001_scanner.l"
{ line_count++; }
	YY_BREAK
case 3:
#line 201 "1905001_scanner.l"
case 4:
#line 202 "1905001_scanner.l"
case 5:
#line 203 "1905001_scanner.l"
case 6:
#line 204 "1905001_scanner.l"
case 7:
#line 205 "1905001_scanner.l"
case 8:
#line 206 "1905001_scanner.l"
case 9:
#line 207 "1905001_scanner.l"
case 10:
#line 208 "1905001_scanner.l"
case 11:
#line 209 "1905001_scanner.l"
case 12:
#line 210 "1905001_scanner.l"
case 13:
#line 211 "1905001_scanner.l"
case 14:
#line 212 "1905001_scanner.l"
case 15:
#line 213 "1905001_scanner.l"
case 16:
#line 214 "1905001_scanner.l"
case 17:
#line 215 "1905001_scanner.l"
case 18:
YY_RULE_SETUP
#line 215 "1905001_scanner.l"
{ printKeyword(); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 218 "1905001_scanner.l"
{ printNum(INTEGER, yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 219 "1905001_scanner.l"
{ printNum(FLOAT, yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 220 "1905001_scanner.l"
{ show_error(TOO_DECIMAL, yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 221 "1905001_scanner.l"
{ show_error(ILL_FORMED, yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 224 "1905001_scanner.l"
{ printIdentifier(); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 225 "1905001_scanner.l"
{ show_error(INVALID_SUFFIX, yytext); }
	YY_BREAK
case 25:
#line 229 "1905001_scanner.l"
case 26:
YY_RULE_SETUP
#line 229 "1905001_scanner.l"
{ printOpPunc("ADDOP"); }
	YY_BREAK
case 27:
#line 231 "1905001_scanner.l"
case 28:
#line 232 "1905001_scanner.l"
case 29:
YY_RULE_SETUP
#line 232 "1905001_scanner.l"
{ printOpPunc("MULOP"); }
	YY_BREAK
case 30:
#line 234 "1905001_scanner.l"
case 31:
YY_RULE_SETUP
#line 234 "1905001_scanner.l"
{ printOpPunc("INCOP"); }
	YY_BREAK
case 32:
#line 236 "1905001_scanner.l"
case 33:
#line 237 "1905001_scanner.l"
case 34:
#line 238 "1905001_scanner.l"
case 35:
#line 239 "1905001_scanner.l"
case 36:
#line 240 "1905001_scanner.l"
case 37:
YY_RULE_SETUP
#line 240 "1905001_scanner.l"
{ printOpPunc("RELOP"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 241 "1905001_scanner.l"
{ printOpPunc("ASSIGNOP"); }
	YY_BREAK
case 39:
#line 243 "1905001_scanner.l"
case 40:
YY_RULE_SETUP
#line 243 "1905001_scanner.l"
{ printOpPunc("LOGICOP"); }
	YY_BREAK
case 41:
#line 245 "1905001_scanner.l"
case 42:
#line 246 "1905001_scanner.l"
case 43:
#line 247 "1905001_scanner.l"
case 44:
#line 248 "1905001_scanner.l"
case 45:
YY_RULE_SETUP
#line 248 "1905001_scanner.l"
{ printOpPunc("BITOP"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 249 "1905001_scanner.l"
{ printOpPunc("NOT"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 250 "1905001_scanner.l"
{ printOpPunc("LPAREN"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 251 "1905001_scanner.l"
{ printOpPunc("RPAREN"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 252 "1905001_scanner.l"
{ printOpPunc("LCURL"); sym.enter_scope(); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 253 "1905001_scanner.l"
{ printOpPunc("RCURL"); sym.exit_scope(); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 254 "1905001_scanner.l"
{ printOpPunc("LSQUARE"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 255 "1905001_scanner.l"
{ printOpPunc("RSQUARE"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 256 "1905001_scanner.l"
{ printOpPunc("COMMA"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 257 "1905001_scanner.l"
{ printOpPunc("SEMICOLON"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 260 "1905001_scanner.l"
{ BEGIN STATE_CHAR; reset(CHAR); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 261 "1905001_scanner.l"
{ BEGIN STATE_STRING; reset(STRING); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 262 "1905001_scanner.l"
{ BEGIN CPP_COMMENT; reset(COMMENT); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 263 "1905001_scanner.l"
{ BEGIN C_COMMENT; reset(COMMENT); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 266 "1905001_scanner.l"
{
							cur_char += generate_special_character(yytext[yyleng - 1]);
							cur_char_raw += yytext;
							char_len++;
						}
	YY_BREAK
case YY_STATE_EOF(STATE_CHAR):
#line 271 "1905001_scanner.l"
{
							string str = "\'" + cur_char_raw;
							show_error(UNFINISHED_CHAR, str);
							BEGIN INITIAL;
						}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 276 "1905001_scanner.l"
{ 
							string str = "\'" + cur_char_raw;
							show_error(UNFINISHED_CHAR, str); 
							line_count++;
							BEGIN INITIAL;
						}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 282 "1905001_scanner.l"
{	 	
							if (char_len == 0) {
								string str = "\'\'";
								show_error(EMPTY_CHAR, str);
							}
							else if (char_len > 1) {
								string str = "\'" + cur_char_raw + "\'";
								show_error(MULTICHAR, str);
							}
							else printChar(cur_char);
							BEGIN INITIAL;
						}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 294 "1905001_scanner.l"
{ 
							cur_char += yytext[0]; 
							cur_char_raw += yytext[0]; 
							char_len++; 
						}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 301 "1905001_scanner.l"
{ 
							cur_string += generate_special_character(yytext[yyleng - 1]); 
							cur_string_raw += yytext; 
						}
	YY_BREAK
case YY_STATE_EOF(STATE_STRING):
#line 305 "1905001_scanner.l"
{
							// if error, print the raw version
							string str = "\"" + cur_string_raw;
							line_count += inside_line;
							show_error(UNFINISHED_STRING, str);
							BEGIN INITIAL;
						}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 312 "1905001_scanner.l"
{ 
							// an example comment like this: 
							//"abc\
							def"
							// not adding to cur_string, as multiline string ultimately is not multiline
							// the aforementioned string is actually "abcdef"
							// so only add to raw string
							inside_line++; 
							cur_string_raw += yytext;
						}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 321 "1905001_scanner.l"
{
							// error as multiline string must have '\' at the end of a line
							// if error, print the raw version
							string str = "\"" + cur_string_raw;
							line_count += inside_line;
							show_error(UNFINISHED_STRING, str);
							line_count++;
							BEGIN INITIAL; 
						}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 330 "1905001_scanner.l"
{
							// print the raw version to log file
							// and the original one to token file
							string str = "\"" + cur_string_raw + "\"";
							string str2 = cur_string;
							if (inside_line == 0) printString(SINGLE_LINE, str, str2);
							else printString(MULTILINE, str, str2);
							line_count += inside_line;
							BEGIN INITIAL;
						}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 340 "1905001_scanner.l"
{ 	cur_string += yytext[0]; 
							cur_string_raw += yytext[0]; 
						}
	YY_BREAK
case YY_STATE_EOF(CPP_COMMENT):
#line 345 "1905001_scanner.l"
{
							string str = "//" + cur_comment;
							printComment(SINGLE_LINE, str);
							line_count += inside_line;
							BEGIN INITIAL;
						}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 351 "1905001_scanner.l"
{
							inside_line++;
							string str = "//" + cur_comment;
							printComment(SINGLE_LINE, str);
							line_count += inside_line;
							BEGIN INITIAL;
						}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 358 "1905001_scanner.l"
{ 
							inside_line++; 
							cur_comment += yytext; 
						}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 362 "1905001_scanner.l"
{ 
							cur_comment += yytext[0]; 
						}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 367 "1905001_scanner.l"
{ 
							inside_line++; 
							cur_comment += "\n"; 
						}
	YY_BREAK
case YY_STATE_EOF(C_COMMENT):
#line 371 "1905001_scanner.l"
{
							string str = "/*" + cur_comment;
							line_count += inside_line;
							show_error(UNFINISHED_COMMENT, str);
							BEGIN INITIAL;
						}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 377 "1905001_scanner.l"
{
							string str = "/*" + cur_comment + "*/";
							printComment(MULTILINE, str);
							line_count += inside_line;
							BEGIN INITIAL;
						}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 383 "1905001_scanner.l"
{ 
							cur_comment += yytext[0]; 
						}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 388 "1905001_scanner.l"
{ return 0; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 389 "1905001_scanner.l"
{ show_error(UNRECOGNIZED, yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 391 "1905001_scanner.l"
ECHO;
	YY_BREAK
#line 1723 "1905001_scanner.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 278 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 278 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 277);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 391 "1905001_scanner.l"


int main(int argc, char** argv) {
	if(argc != 2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1], "r");
	if(fin == NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
	logout.open("1905001_log.txt");
	tokenout.open("1905001_token.txt");

	yyin = fin;
	yylex();
	fclose(yyin);

	sym.print('A', logout);
	logout << "Total lines: " << line_count << endl;
	logout << "Total errors: " << error_count << endl;

	tokenout.close();
	logout.close();
	return 0;
}

